### PR TITLE
feat: Add home yap page.

### PR DESCRIPTION
**Pull request by IRONICBo**
image

Use yap web engine and tailwind to create home page, binding with yap render.

### CODE REVIEW

**Comment by IRONICBo** [comment]
@@Kasey0727 @Baihhh  Please review for web page.

**Comment by Baihhh** [comment]
LGTM

**Comment by Kasey0727** [comment]
LGTM

**Comment by IRONICBo** [comment]
Support File Server. https://github.com/goplus/yap/issues/20

**Pull request merged**
