### PR TITLE
Add code linter

### PR DESCRIPTION
**Pull request by linjie7674**
# Feature
Add code linter by using `golangci-lint`

# Test Results
image

### CODE REVIEW

**Review by IRONICBo — CHANGES_REQUESTED** [review]
Please skip lint for `_gen.go`.

**Comment by linjie7674** [comment]
> Please skip lint for `_gen.go`.

OK, I updated it.

**Comment by IRONICBo** [comment]
It seems that the ci lint can not recognize the gox file. @linjie7674 

image

**Comment by linjie7674** [comment]
> It seems that the ci lint can not recognize the gox file. @linjie7674
> 
> image

In the action summary, we can see the files that do not conform to the golanglint specification, which in this case contain the gox files.
image

**Comment by IRONICBo** [comment]
Looks good, we will update `gox` file later.

**Review by IRONICBo — APPROVED** [review]
LGTM

**Pull request merged**
